### PR TITLE
fix: separate owner kinds for uncontrolledOnly

### LINKED ISSUE #1142: Only Pods and Jobs with expected controllers should be filtered when uncontrolledOnly is set
## Background
Currently Policy Reporter in default configuration "deduplicates" reports for controllers:
```
sourceFilters:
  - selector:
      source: kyverno
    uncontrolledOnly: true
    disableClusterReports: false
    kinds:
      exclude: [ReplicaSet]
```

This filters out:
- Pods, if they are controlled by any of `"ReplicaSet", "DaemonSet", "CronJob", "Job", "Job", "StatefulSet"`:
https://github.com/kyverno/policy-reporter/blob/846b6d9f1d30b2fdcfc1688e0a03ed55db285f43/pkg/report/source_filter.go#L94
https://github.com/kyverno/policy-reporter/blob/846b6d9f1d30b2fdcfc1688e0a03ed55db285f43/pkg/report/source_filter.go#L131
- Jobs, if they're controlled by any of `"ReplicaSet", "DaemonSet", "CronJob", "Job", "Job", "StatefulSet"`:
https://github.com/kyverno/policy-reporter/blob/846b6d9f1d30b2fdcfc1688e0a03ed55db285f43/pkg/report/source_filter.go#L109
https://github.com/kyverno/policy-reporter/blob/846b6d9f1d30b2fdcfc1688e0a03ed55db285f43/pkg/report/source_filter.go#L131
- Any ReplicaSets:
https://github.com/kyverno/policy-reporter/blob/846b6d9f1d30b2fdcfc1688e0a03ed55db285f43/pkg/report/source_filter.go#L84-L87

## Expected behavior

- Pods are only filtered out if they're owned by `ReplicaSet`, `DaemonSet`, `Job`, `StatefulSet`
- Jobs are only filtered out if they're owned by `CronJob`
- ReplicaSets might be improved too, see #1143 

## Impact
Current defaults allow trivial "bypasses" of policy-reporter: for example, by creating a Job with a completely unrelated owner reference (not a CronJob) – controllers don't usually try to watch unrelated resources, so the ownerReferences will stay there.

PoC:
```
❯ k logs policy-reporter-... | grep evil-job-v2
debug	filter controlled job resource	{"namespace": "default", "report": "...", "kind": "Job", "name": "evil-job-v2", "namespace": "default"}
debug	filter controlled pod resource	{"namespace": "default", "report": "...", "kind": "Pod", "name": "evil-job-v2-phj85", "namespace": "default"}
```

While on the Job:
```
❯ k get job evil-job-v2 -oyaml | yq -r .metadata.ownerReferences
- apiVersion: apps/v1
  blockOwnerDeletion: true
  controller: true
  kind: ReplicaSet
  name: normal-app-repicaset-74d7b8894b
  uid: ...
```

I believe that the same thing can be achieved by creating a Pod directly with a CronJob in owner references, which should never be there under normal circumstances.

Maybe configuration should be made more explicit and allow listing additional owner-resource references, so it will be possible to list more kinds with their respective owner kinds.

### PR DESCRIPTION
**Pull request by stek29**
Fixes #1142

### CODE REVIEW

File: pkg/report/source_filter.go [hunk 1]
```diff
@@ -128,9 +128,11 @@ func NewSourceFilter(pods PodClient, jobs JobClient, validations []SourceValidat
 	return &SourceFilter{pods: pods, jobs: jobs, validations: validations}
 }
 
-var controller = []string{"ReplicaSet", "DaemonSet", "CronJob", "Job", "Job", "StatefulSet"}
+var podControllers = []string{"ReplicaSet", "DaemonSet", "Job", "StatefulSet"}
 
-func Uncontrolled(owner []metav1.OwnerReference) bool {
+var jobControllers = []string{"CronJob"}
+
+func Uncontrolled(owner []metav1.OwnerReference, controllers []string) bool {
```
Comment (stek29) [inline pkg/report/source_filter.go:135]: this is potentially backwards incompatible, please tell me if backwards compatibility for this function should be preserved for possible external usage of it

Comment (fjogeleit) [reply pkg/report/source_filter.go:135]: no, this change is fine. thanks
